package com.artemis.stress.xml;

import com.artemis.stress.config.StressConfig;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.w3c.dom.Document;
import org.w3c.dom.Element;

import javax.xml.parsers.DocumentBuilder;
import javax.xml.parsers.DocumentBuilderFactory;
import javax.xml.parsers.ParserConfigurationException;
import javax.xml.transform.*;
import javax.xml.transform.dom.DOMSource;
import javax.xml.transform.stream.StreamResult;
import javax.xml.transform.stream.StreamSource;
import java.io.*;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.time.Instant;
import java.util.UUID;
import java.util.concurrent.ThreadLocalRandom;

/**
 * Generates XML payloads that are:
 * <ol>
 *   <li>Well-formed (built via the W3C DOM API, never string concatenation).</li>
 *   <li>Schema-conformant (namespace {@code urn:stress:v1}, matches
 *       {@code stress-message.xsd}).</li>
 *   <li>Injected with a globally unique {@code <NumericId>} generated by a
 *       shared {@link MessageIdGenerator} before every send.</li>
 * </ol>
 *
 * <h3>Two operating modes</h3>
 * <ul>
 *   <li><b>Generated mode</b> (default) — synthesises a complete DOM document
 *       from scratch, padding the {@code <Padding>} element to reach
 *       {@code messageSize} bytes.</li>
 *   <li><b>Template mode</b> — parses a user-supplied XML file into a DOM
 *       tree once at startup.  Before each send the tree is cloned, the
 *       {@code <NumericId>} element is injected / updated in the clone's
 *       {@code Header}, and standard placeholders (${SEQ}, ${UUID}, etc.)
 *       are substituted via an identity XSLT with parameters.</li>
 * </ul>
 *
 * <p><b>Thread-safety:</b> {@link DocumentBuilder} and {@link Transformer}
 * are NOT thread-safe, so each call to {@link #generate} obtains them from
 * thread-local factories.</p>
 */
public class XmlPayloadGenerator {

    private static final Logger log = LoggerFactory.getLogger(XmlPayloadGenerator.class);

    /** Target XML namespace — must match the XSD {@code targetNamespace}. */
    static final String NS = "urn:stress:v1";

    private final int targetSize;
    private final MessageIdGenerator idGenerator;

    /** Pre-parsed template DOM tree (null in generated mode). */
    private final Document templateDoc;

    // ── Thread-local XML factories ─────────────────────────────────────────

    private static final ThreadLocal<DocumentBuilder> TL_BUILDER =
            ThreadLocal.withInitial(() -> {
                try {
                    DocumentBuilderFactory dbf = DocumentBuilderFactory.newInstance();
                    dbf.setNamespaceAware(true);
                    // Harden against XXE
                    dbf.setFeature("http://apache.org/xml/features/disallow-doctype-decl", true);
                    dbf.setFeature("http://xml.org/sax/features/external-general-entities", false);
                    dbf.setFeature("http://xml.org/sax/features/external-parameter-entities", false);
                    return dbf.newDocumentBuilder();
                } catch (ParserConfigurationException e) {
                    throw new RuntimeException("Cannot create DocumentBuilder", e);
                }
            });

    private static final ThreadLocal<Transformer> TL_TRANSFORMER =
            ThreadLocal.withInitial(() -> {
                try {
                    TransformerFactory tf = TransformerFactory.newInstance();
                    tf.setFeature(javax.xml.XMLConstants.FEATURE_SECURE_PROCESSING, true);
                    Transformer t = tf.newTransformer();
                    t.setOutputProperty(OutputKeys.ENCODING, "UTF-8");
                    t.setOutputProperty(OutputKeys.INDENT, "yes");
                    t.setOutputProperty("{http://xml.apache.org/xslt}indent-amount", "2");
                    t.setOutputProperty(OutputKeys.OMIT_XML_DECLARATION, "no");
                    return t;
                } catch (TransformerConfigurationException e) {
                    throw new RuntimeException("Cannot create Transformer", e);
                }
            });

    // ── Constructor ────────────────────────────────────────────────────────

    public XmlPayloadGenerator(StressConfig config, MessageIdGenerator idGenerator)
            throws Exception {
        this.targetSize  = config.getMessageSize();
        this.idGenerator = idGenerator;

        if (config.getXmlTemplatePath() != null) {
            templateDoc = parseTemplate(config.getXmlTemplatePath());
            log.info("XML template loaded from {} — will inject <NumericId> on each send",
                    config.getXmlTemplatePath());
        } else {
            templateDoc = null;
            log.info("Using generated DOM XML payloads (~{} bytes, namespace={})",
                    targetSize, NS);
        }
    }

    // ── Public API ─────────────────────────────────────────────────────────

    /**
     * Generates a schema-conformant XML string with a unique {@link #idGenerator}-
     * issued {@code <NumericId>} embedded in the {@code <Header>}.
     *
     * @param seq        globally unique sequence number (== NumericId in generated mode)
     * @param producerId producer thread identifier
     * @return serialised XML, ready to send as a JMS {@link jakarta.jms.TextMessage}
     */
    public String generate(long seq, int producerId) {
        long numericId = idGenerator.next();   // ← unique, never duplicated
        if (templateDoc != null) {
            return renderTemplate(numericId, seq, producerId);
        }
        return buildGeneratedDocument(numericId, seq, producerId);
    }

    // ── Generated mode ─────────────────────────────────────────────────────

    private String buildGeneratedDocument(long numericId, long seq, int producerId) {
        Document doc = TL_BUILDER.get().newDocument();

        // <StressMessage xmlns="urn:stress:v1">
        Element root = doc.createElementNS(NS, "StressMessage");
        doc.appendChild(root);

        root.appendChild(buildHeader(doc, numericId, seq, producerId));
        root.appendChild(buildBody(doc, seq));

        // Padding — serialise a first time to measure, then add padding element
        String firstPass = serialise(doc);
        int deficit = targetSize - firstPass.length();
        if (deficit > 0) {
            Element padding = doc.createElementNS(NS, "Padding");
            padding.setTextContent(buildPadding(deficit));
            root.appendChild(padding);
        }

        return serialise(doc);
    }

    private Element buildHeader(Document doc, long numericId, long seq, int producerId) {
        Element header = doc.createElementNS(NS, "Header");

        // ── NumericId — THE unique numeric identifier ──────────────────────
        Element nid = doc.createElementNS(NS, "NumericId");
        nid.setTextContent(String.valueOf(numericId));
        header.appendChild(nid);

        appendText(doc, header, "MessageId",  UUID.randomUUID().toString());
        appendText(doc, header, "Sequence",   String.valueOf(seq));
        appendText(doc, header, "ProducerId", String.valueOf(producerId));
        appendText(doc, header, "Timestamp",  Instant.now().toString());
        appendText(doc, header, "Version",    "1.1");

        return header;
    }

    private Element buildBody(Document doc, long seq) {
        ThreadLocalRandom rng = ThreadLocalRandom.current();
        double unitPrice = Math.round(rng.nextDouble(0.01, 99_999.99) * 100.0) / 100.0;
        int    qty       = rng.nextInt(1, 1000);
        double total     = Math.round(unitPrice * qty * 100.0) / 100.0;

        Element body  = doc.createElementNS(NS, "Body");
        Element order = doc.createElementNS(NS, "Order");
        body.appendChild(order);

        appendText(doc, order, "OrderId", String.format("ORD-%08d", seq % 100_000_000L));
        appendText(doc, order, "Status",  randomStatus());

        Element customer = doc.createElementNS(NS, "Customer");
        appendText(doc, customer, "Id",    String.format("CUST-%05d", seq % 100_000L));
        appendText(doc, customer, "Name",  "Customer " + (seq % 100_000L));
        appendText(doc, customer, "Email", "customer" + (seq % 100_000L) + "@example.com");
        order.appendChild(customer);

        Element items = doc.createElementNS(NS, "Items");
        Element item  = doc.createElementNS(NS, "Item");
        appendText(doc, item, "SKU",       String.format("SKU-%06d", rng.nextInt(1, 1_000_000)));
        appendText(doc, item, "Quantity",  String.valueOf(qty));
        appendText(doc, item, "UnitPrice", String.format("%.2f", unitPrice));
        appendText(doc, item, "Total",     String.format("%.2f", total));
        items.appendChild(item);
        order.appendChild(items);

        appendText(doc, order, "Total", String.format("%.2f", total));

        return body;
    }

    // ── Template mode ──────────────────────────────────────────────────────

    /**
     * Parses the user template into a DOM tree.
     * We do this ONCE at startup; each call to {@link #renderTemplate} deep-
     * clones the tree so the original remains untouched.
     */
    private Document parseTemplate(String path) throws Exception {
        DocumentBuilder db = TL_BUILDER.get();
        try (InputStream is = Files.newInputStream(Paths.get(path))) {
            Document d = db.parse(is);
            d.getDocumentElement().normalize();
            return d;
        }
    }

    /**
     * Clones the template, injects / updates {@code <NumericId>} and substitutes
     * text-node placeholders throughout the document.
     */
    private String renderTemplate(long numericId, long seq, int producerId) {
        // Deep-clone so the master template is never mutated
        Document doc = (Document) templateDoc.cloneNode(true);

        // Inject NumericId into Header (create or overwrite)
        injectNumericId(doc, numericId);

        // Substitute text-node placeholders
        String ts  = Instant.now().toString();
        String uid = UUID.randomUUID().toString();
        long   rnd = ThreadLocalRandom.current().nextLong(1_000_000);
        substitutePlaceholders(doc.getDocumentElement(),
                numericId, seq, producerId, ts, uid, rnd);

        return serialise(doc);
    }

    /**
     * Finds or creates the {@code <Header>/<NumericId>} element and sets its
     * text content to the supplied value.
     *
     * <p>Works for both the bundled schema (namespace {@code urn:stress:v1})
     * and namespaced templates that use any prefix for that namespace.</p>
     */
    private void injectNumericId(Document doc, long numericId) {
        org.w3c.dom.NodeList headers = doc.getElementsByTagNameNS(NS, "Header");

        if (headers.getLength() == 0) {
            // Fallback: try without namespace (user template may omit it)
            headers = doc.getElementsByTagName("Header");
        }

        if (headers.getLength() == 0) {
            log.warn("Template has no <Header> element — cannot inject <NumericId>. " +
                     "Add a <Header> section or use generated mode.");
            return;
        }

        Element header = (Element) headers.item(0);

        // Look for an existing NumericId child
        org.w3c.dom.NodeList existing = header.getElementsByTagNameNS(NS, "NumericId");
        if (existing.getLength() == 0) {
            existing = header.getElementsByTagName("NumericId");
        }

        if (existing.getLength() > 0) {
            // Update the existing element
            existing.item(0).setTextContent(String.valueOf(numericId));
        } else {
            // Create a new NumericId as the FIRST child of Header
            Element nid = doc.createElementNS(NS, "NumericId");
            nid.setTextContent(String.valueOf(numericId));
            header.insertBefore(nid, header.getFirstChild());
            log.debug("Injected <NumericId> into <Header> (was absent in template)");
        }
    }

    /**
     * Recursively walks all text nodes and replaces placeholder tokens.
     * Attribute values are also processed.
     */
    private void substitutePlaceholders(org.w3c.dom.Node node,
                                        long numericId, long seq, int producerId,
                                        String ts, String uid, long rnd) {
        if (node.getNodeType() == org.w3c.dom.Node.TEXT_NODE) {
            String val = node.getNodeValue();
            if (val != null && val.contains("${")) {
                val = val.replace("${NUMERIC_ID}",  String.valueOf(numericId))
                         .replace("${SEQ}",          String.valueOf(seq))
                         .replace("${UUID}",         uid)
                         .replace("${TS}",           ts)
                         .replace("${PRODUCER_ID}",  String.valueOf(producerId))
                         .replace("${RANDOM}",       String.valueOf(rnd));
                node.setNodeValue(val);
            }
        }
        // Process attributes
        if (node.getAttributes() != null) {
            for (int i = 0; i < node.getAttributes().getLength(); i++) {
                substitutePlaceholders(node.getAttributes().item(i),
                        numericId, seq, producerId, ts, uid, rnd);
            }
        }
        // Recurse children
        org.w3c.dom.NodeList children = node.getChildNodes();
        for (int i = 0; i < children.getLength(); i++) {
            substitutePlaceholders(children.item(i),
                    numericId, seq, producerId, ts, uid, rnd);
        }
    }

    // ── Serialisation ──────────────────────────────────────────────────────

    private String serialise(Document doc) {
        try {
            StringWriter sw = new StringWriter(targetSize + 256);
            TL_TRANSFORMER.get().transform(new DOMSource(doc), new StreamResult(sw));
            return sw.toString();
        } catch (TransformerException e) {
            throw new RuntimeException("Failed to serialise XML document", e);
        }
    }

    // ── Utilities ──────────────────────────────────────────────────────────

    private void appendText(Document doc, Element parent, String localName, String value) {
        Element el = doc.createElementNS(NS, localName);
        el.setTextContent(value);
        parent.appendChild(el);
    }

    private String buildPadding(int length) {
        char[] alphabet = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789".toCharArray();
        ThreadLocalRandom rng = ThreadLocalRandom.current();
        char[] chars = new char[Math.max(length, 0)];
        for (int i = 0; i < chars.length; i++) {
            chars[i] = alphabet[rng.nextInt(alphabet.length)];
        }
        return new String(chars);
    }

    private static final String[] STATUSES = {
        "PENDING", "CONFIRMED", "PROCESSING", "SHIPPED", "DELIVERED", "CANCELLED"
    };

    private String randomStatus() {
        return STATUSES[ThreadLocalRandom.current().nextInt(STATUSES.length)];
    }
}
