package com.artemis.stress.xml;

import com.artemis.stress.config.StressConfig;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.Collections;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import java.util.concurrent.*;
import java.util.concurrent.atomic.AtomicInteger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

import static org.junit.jupiter.api.Assertions.*;

/**
 * Tests that:
 * <ol>
 *   <li>The {@link MessageIdGenerator} never issues duplicate IDs, even under
 *       heavy concurrent access.</li>
 *   <li>Every document generated by {@link XmlPayloadGenerator} validates
 *       against the bundled {@code stress-message.xsd}.</li>
 *   <li>The {@code <NumericId>} embedded in the document matches the ID
 *       returned by the generator.</li>
 *   <li>No two documents share the same {@code <NumericId>}.</li>
 * </ol>
 */
class XmlGeneratorTest {

    private static final int THREAD_COUNT = 16;
    private static final int MESSAGES_PER_THREAD = 500;  // 8 000 total
    private static final Pattern NUMERIC_ID_PATTERN =
            Pattern.compile("<(?:[^:>]+:)?NumericId>(\\d+)</(?:[^:>]+:)?NumericId>");

    private MessageIdGenerator idGenerator;
    private XmlSchemaValidator validator;
    private XmlPayloadGenerator generator;

    @BeforeEach
    void setUp() throws Exception {
        idGenerator = new MessageIdGenerator(1L);
        validator   = new XmlSchemaValidator();   // bundled XSD

        StressConfig config = new StressConfig();
        config.setMessageSize(1024);
        generator = new XmlPayloadGenerator(config, idGenerator);
    }

    // ─── MessageIdGenerator tests ─────────────────────────────────────────────

    @Test
    void singleThreadSequential() {
        long prev = 0;
        for (int i = 0; i < 10_000; i++) {
            long id = idGenerator.next();
            assertTrue(id > prev, "ID must be strictly greater than previous");
            prev = id;
        }
        assertEquals(10_000L, idGenerator.lastIssued());
    }

    @Test
    void startValueIsRespected() {
        MessageIdGenerator gen = new MessageIdGenerator(5_000_000L);
        assertEquals(5_000_000L, gen.next());
        assertEquals(5_000_001L, gen.next());
    }

    @Test
    void startValueBelowOneFails() {
        assertThrows(IllegalArgumentException.class, () -> new MessageIdGenerator(0));
        assertThrows(IllegalArgumentException.class, () -> new MessageIdGenerator(-1));
    }

    @Test
    void noDuplicatesUnderConcurrency() throws InterruptedException {
        int total = THREAD_COUNT * MESSAGES_PER_THREAD;
        MessageIdGenerator gen = new MessageIdGenerator(1L);
        Set<Long> ids = Collections.synchronizedSet(new HashSet<>(total));
        AtomicInteger collisions = new AtomicInteger(0);

        ExecutorService exec = Executors.newFixedThreadPool(THREAD_COUNT);
        CountDownLatch latch = new CountDownLatch(THREAD_COUNT);

        for (int t = 0; t < THREAD_COUNT; t++) {
            exec.submit(() -> {
                try {
                    for (int m = 0; m < MESSAGES_PER_THREAD; m++) {
                        long id = gen.next();
                        if (!ids.add(id)) {
                            collisions.incrementAndGet();
                        }
                    }
                } finally {
                    latch.countDown();
                }
            });
        }

        latch.await(30, TimeUnit.SECONDS);
        exec.shutdown();

        assertEquals(0, collisions.get(),
                "No duplicate IDs allowed — found " + collisions.get() + " collision(s)");
        assertEquals(total, ids.size(),
                "Expected " + total + " unique IDs");
        assertEquals((long) total, gen.lastIssued(),
                "lastIssued() must match total issued count");
    }

    // ─── XmlPayloadGenerator + Schema validation tests ────────────────────────

    @Test
    void generatedDocumentPassesSchemaValidation() {
        String xml = generator.generate(1L, 0);
        assertNotNull(xml);
        assertDoesNotThrow(() -> validator.validate(xml),
                "Generated document must be schema-valid");
    }

    @Test
    void numericIdIsEmbeddedCorrectly() {
        // Generate a document and extract the NumericId from the XML text
        String xml = generator.generate(42L, 0);
        long extractedId = extractNumericId(xml);

        assertTrue(extractedId >= 1,
                "NumericId must be >= 1, got: " + extractedId);
    }

    @Test
    void allDocumentsHaveUniqueNumericIds() throws Exception {
        int count = 200;
        Set<Long> seenIds = new HashSet<>(count);

        for (int i = 0; i < count; i++) {
            String xml = generator.generate(i + 1L, 0);
            long id = extractNumericId(xml);
            assertTrue(seenIds.add(id),
                    "Duplicate NumericId found: " + id + " at iteration " + i);
        }
        assertEquals(count, seenIds.size());
    }

    @Test
    void concurrentGenerationHasNoIdDuplicates() throws InterruptedException {
        int total = THREAD_COUNT * MESSAGES_PER_THREAD;
        List<String> documents = Collections.synchronizedList(new ArrayList<>(total));

        ExecutorService exec = Executors.newFixedThreadPool(THREAD_COUNT);
        CountDownLatch latch = new CountDownLatch(THREAD_COUNT);

        for (int t = 0; t < THREAD_COUNT; t++) {
            final int tid = t;
            exec.submit(() -> {
                try {
                    for (int m = 0; m < MESSAGES_PER_THREAD; m++) {
                        documents.add(generator.generate(m + 1L, tid));
                    }
                } finally {
                    latch.countDown();
                }
            });
        }

        latch.await(60, TimeUnit.SECONDS);
        exec.shutdown();

        assertEquals(total, documents.size());

        // Verify all IDs are unique
        Set<Long> ids = new HashSet<>(total);
        for (String xml : documents) {
            long id = extractNumericId(xml);
            assertTrue(ids.add(id), "Duplicate NumericId in concurrent generation: " + id);
        }
        assertEquals(total, ids.size(), "Expected " + total + " unique IDs");
    }

    @Test
    void concurrentGenerationAllDocumentsSchemaValid() throws InterruptedException {
        int total = THREAD_COUNT * 50;
        AtomicInteger failures = new AtomicInteger(0);

        ExecutorService exec = Executors.newFixedThreadPool(THREAD_COUNT);
        CountDownLatch latch = new CountDownLatch(THREAD_COUNT);

        for (int t = 0; t < THREAD_COUNT; t++) {
            final int tid = t;
            exec.submit(() -> {
                try {
                    for (int m = 0; m < 50; m++) {
                        String xml = generator.generate(m + 1L, tid);
                        try {
                            validator.validate(xml);
                        } catch (XmlSchemaValidator.XmlValidationException e) {
                            failures.incrementAndGet();
                            System.err.println("Validation failure: " + e.getMessage());
                            System.err.println("Document:\n" + xml);
                        }
                    }
                } finally {
                    latch.countDown();
                }
            });
        }

        latch.await(60, TimeUnit.SECONDS);
        exec.shutdown();

        assertEquals(0, failures.get(),
                failures.get() + " document(s) failed schema validation");
    }

    // ─── Helpers ─────────────────────────────────────────────────────────────

    private long extractNumericId(String xml) {
        Matcher m = NUMERIC_ID_PATTERN.matcher(xml);
        assertTrue(m.find(), "No <NumericId> element found in:\n" + xml);
        return Long.parseLong(m.group(1));
    }
}
